/**
 * The morning quote bank (Kiron, 2026-09-30: "make a bank of 200 or so that I
 * can look through"). One line goes into each morning check-in, between
 * "Good morning" and the goal question.
 *
 * Rules for adding or editing: short (one line on a phone), positive,
 * original rather than attributed to anyone famous (so nothing is misquoted),
 * no em dashes. Delete freely; the rotation adapts to however many there are.
 *
 * Rotation: by day of the year, so everyone gets the same line on the same day
 * and nobody sees a repeat until the whole bank has gone round.
 */
export const MORNING_QUOTES: string[] = [
  'Small steps, taken daily, cover a surprising distance.',
  'You do not need a perfect day. You need a started one.',
  'Consistency is quiet, and it is undefeated.',
  'Every application is a vote for the person you are becoming.',
  'The work you do when nobody is watching is the work that gets noticed.',
  'Progress beats perfection, every single day.',
  'One good hour can change the direction of a week.',
  'Doors open for people who keep knocking.',
  'Today is a fresh page. Write one good line on it.',
  'Momentum is built, not found.',
  'You are closer than you were yesterday.',
  'Discipline is choosing what you want most over what you want now.',
  'The best time to start was yesterday. The next best is now.',
  'A small win before lunch sets the tone for the whole day.',
  'Effort compounds, even when you cannot see it yet.',
  'Show up for yourself the way you would for a friend.',
  'Every no brings you one step closer to a yes.',
  'Keep going. Future you is counting on it.',
  'Courage is sending the message anyway.',
  'You were built for more than waiting.',
  'Motion creates emotion. Start, and the feeling follows.',
  'Do the next right thing, then the one after that.',
  'Hard days are part of the path, not the end of it.',
  'The goal is not to be perfect. The goal is to keep going.',
  'Your story is still being written. Make today a good chapter.',
  'Clarity comes from action, not from thinking harder.',
  'Tiny progress is still progress.',
  'Today counts, even if it only counts a little.',
  'The effort you put in now is the story you will tell later.',
  'Be stubborn about the goal and flexible about the route.',
  'A job search is a skill, and skills grow with practice.',
  'Rejection is information, not a verdict.',
  'Win the morning and the day gets easier.',
  'You only need to be braver than your excuses.',
  'Every expert was once a beginner who kept going.',
  'Build the habit and the results will follow.',
  'Do it scared. Do it tired. Just do it today.',
  'You cannot control the outcome, but you can control the effort.',
  'Each day you show up, you get a little harder to overlook.',
  'Your future employer is out there. Make it easy for them to find you.',
  'Today is another chance to get it right.',
  'Great things are built one ordinary day at a time.',
  'The hardest part is starting. After that it is just the next step.',
  'Believe in the work, even before it pays off.',
  'Patience and persistence make an unbeatable team.',
  'You have survived every hard day so far. This one is no different.',
  'Let today be the day you surprise yourself.',
  'Keep your promises to yourself. They matter most.',
  'Direction matters more than speed.',
  'What you do daily matters more than what you do once in a while.',
  'You are allowed to be a work in progress and still move forward.',
  'The right role is looking for someone exactly like you.',
  'A little better than yesterday is a great goal.',
  'Confidence is built by keeping small commitments.',
  'The only failed application is the one you never sent.',
  'Energy flows where attention goes.',
  'Focus on the next hour, not the next month.',
  'Every message you send plants a seed.',
  'You bring something no one else can.',
  'Stay curious. Stay consistent. Stay kind to yourself.',
  'Good things take time, and time is on your side when you keep going.',
  'You do not have to see the whole staircase. Take the first step.',
  'Showing up is half the work. Today, show up.',
  'The people who get hired are the people who keep applying.',
  'Keep planting. Harvest season is coming.',
  'Your effort today is a gift to your future self.',
  'Begin with what you have. It is enough to start.',
  'Resilience is just getting back up one more time than you fall.',
  'A clear plan turns a big goal into a small task.',
  'You are not behind. You are on your own path.',
  'Make today the day you do the thing you have been putting off.',
  'Quiet persistence outlasts loud talent.',
  'Every day is a new chance to be the candidate they remember.',
  'You grow in the moments you choose not to quit.',
  'Put in the reps. The results are keeping score.',
  'The shortcut is doing the work well.',
  'Doubt stops more people than failure ever does.',
  'Do your best today. That is always enough.',
  'Pressure is a privilege. It means something matters.',
  'Your value does not change because a recruiter did not reply.',
  'Stack the good days and the good weeks take care of themselves.',
  'The best opportunities often start with a simple hello.',
  'Commit to the process and trust it to carry you.',
  'You are one conversation away from a new chapter.',
  'The version of you who gets the job does the work today.',
  'Keep moving. Standing still is the only real setback.',
  'A focused hour beats a distracted day.',
  'Make it easy for good things to find you.',
  'Consistency turns ordinary effort into extraordinary results.',
  'Hope is a good start. A plan is even better.',
  'Take the step in front of you. That is all today asks.',
  'You have done hard things before. You can do this one.',
  'Let your actions speak louder than your worries.',
  'Every small improvement adds up to a big difference.',
  'Today, be the person who follows through.',
  'Great careers are built from brave little decisions.',
  'Trust yourself. You know more than you think.',
  'Nothing changes until you do.',
  'You are exactly where you need to be to start.',
  'Aim for progress you can be proud of by tonight.',
  'Your persistence is your superpower.',
  'Keep the promise you made to yourself yesterday.',
  'Every attempt teaches you something the last one could not.',
  'The door you want may be the next one you knock on.',
  'Be proud of how far you have come, and excited for where you are going.',
  'Dream big. Start small. Act today.',
  'A good day starts with a clear decision.',
  'The best preparation for tomorrow is doing today well.',
  'Belief gets you started. Effort gets you there.',
  'Every step forward is a step away from where you were.',
  'Success is small efforts, repeated until they add up.',
  'Choose progress over comfort today.',
  'Focus on what you can do, not on what you cannot.',
  'Your next opportunity could come from today’s effort.',
  'Hard work beats waiting, every time.',
  'Make today’s effort something tomorrow will thank you for.',
  'You are building something, even on the slow days.',
  'The right people notice consistency.',
  'Start before you feel ready. Ready arrives on the way.',
  'Every day you try is a day you did not give up.',
  'Treat your search like a project, and you will manage it like a pro.',
  'Show the world what you can do, one application at a time.',
  'Keep your head up and your applications going out.',
  'Your break is coming. Be ready when it does.',
  'Good things grow from steady effort.',
  'Make one bold move today.',
  'The difference between a dream and a goal is a plan.',
  'Practice has a funny way of looking like luck.',
  'You are not starting over. You are starting with experience.',
  'Be the reason your future is brighter.',
  'The road is long, but you are already on it.',
  'A setback is a setup for a comeback.',
  'Lean into the work. That is where the growth is.',
  'Stay the course. The view is worth it.',
  'Small and steady wins the race.',
  'Every morning is a reset button. Press it.',
  'Your best work is still ahead of you.',
  'Let today be proof of what you can do.',
  'Stay patient. Stay persistent. Stay positive.',
  'Doing it badly is better than not doing it at all. Improve as you go.',
  'The effort is never wasted, even when it feels invisible.',
  'Keep showing up. That is how luck finds you.',
  'Turn "I should" into "I did" today.',
  'Make space for your goal before the day fills up.',
  'One more try could be the one.',
  'You are worth the effort it takes.',
  'Keep calm and keep applying.',
  'Your commitment today shapes your career tomorrow.',
  'Follow through, even on the small things.',
  'Great things come to those who keep going.',
  'Every day is practice for the interview you have not had yet.',
  'Believe in the long game.',
  'You do not have to be the best. You have to be consistent.',
  'Take pride in the work, whatever the result.',
  'The best is yet to come, and you are working towards it.',
  'Plant the seeds today. The shade comes later.',
  'Choose one thing and do it well.',
  'Stay hungry, stay humble, stay consistent.',
  'Your hard work is building a foundation.',
  'Keep chipping away. The block always gives.',
  'Opportunities multiply when you seize them.',
  'How you show up today shapes where you land tomorrow.',
  'Action is the antidote to anxiety.',
  'Take the stairs today. Every step up is yours to keep.',
  'Make today count, then do it again tomorrow.',
  'Push through the resistance. It means you are growing.',
  'You are the author of your next chapter.',
  'The first step is always the hardest. Take it anyway.',
  'Stay focused on the goal, not the obstacles.',
  'Every effort brings you closer to the breakthrough.',
  'Keep going. You are doing better than you think.',
  'Persistence pays, often when you least expect it.',
  'Invest in yourself today. It pays the best interest.',
  'Let every no sharpen your next yes.',
  'Be relentless about the things that matter.',
  'Today is a good day to take a step forward.',
  'Your future is created by what you do today, not tomorrow.',
  'Long roads are walked one short step at a time.',
  'Rise, reset, and go again.',
  'Keep your eyes on the goal and your feet moving.',
  'Consistency is the bridge between goals and results.',
  'Do something today that your future self will thank you for.',
  'Every day is a chance to get a little better.',
  'When it gets hard, the way forward is still forward.',
  'Stay committed to your decisions, flexible in your approach.',
  'Small daily improvements lead to stunning long-term results.',
  'Start strong, stay steady, finish proud.',
  'Believe in the process. It believes in you.',
  'Keep knocking. Doors open for the persistent.',
  'Your effort is your edge.',
  'Keep building. Your moment is on its way.',
  'Do the work others skip, and you will stand out.',
  'The grind is temporary. The growth is permanent.',
  'You are one decision away from a better day.',
  'Every applicant who got hired once felt exactly where you are now.',
  'Make today the day that changes the story.',
  'Go get it. Today is yours.',
  'A tailored application today is worth ten rushed ones.',
  'Reach out to one new person today. That is how doors appear.',
  'Your consistency is the proof your future employer is looking for.',
];
