// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isProduction = process.env["NODE_ENV"] === "production";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Only use the direct (non-pooled) URL locally; in production the pooler
    // handles connections and the direct URL is unreachable from Railway.
    ...(isProduction ? {} : { directUrl: process.env["DIRECT_URL"] }),
  },
});
