// Outreach Follow-Up Ladder Templates
// Cadence: Day 0 (touch 1), Day 4 (touch 2), Day 6 (touch 3)
// Auto-close: 7 days after touch 3 with no reply

export const OUTREACH_CADENCE = [0, 4, 6];
export const CLOSING_WINDOW_DAYS = 7;

export type TouchTemplate = {
  label: string;
  render: (params: { firstName: string; company: string; topic: string }) => string;
  coachingTip: string;
};

// Touch 1: The existing opener (personalised: name, company, topic, specific question)
// This is generated by the LLM in the OutreachTemplates component

// Touch 2: Friendly bump - short, warm, no guilt-tripping
export const TOUCH_2_TEMPLATE: TouchTemplate = {
  label: 'Friendly bump (Touch 2)',
  render: ({ firstName }) =>
    `Hi ${firstName}, just floating this back up in case it got buried. No pressure at all — I know how full inboxes get.`,
  coachingTip: 'Keep it light. The goal is visibility, not pressure. If they were going to reply, this removes friction; if not, you\'re still leaving a good impression.',
};

// Touch 3: Graceful close - "I get it, you're busy, won't bug you again, door's open"
export const TOUCH_3_TEMPLATE: TouchTemplate = {
  label: 'Graceful close (Touch 3)',
  render: ({ firstName }) =>
    `Hi ${firstName}, no worries at all — I totally get that you're busy and this isn't always the right time. I won't follow up again, but if things change or you ever want to connect, my door's open. All the best!`,
  coachingTip: 'This is the dignity close. It leaves the relationship intact and occasionally triggers a "sorry, meant to reply" response. The door genuinely stays open.',
};

export function getTemplateForTouch(touchNumber: number): TouchTemplate | null {
  if (touchNumber === 2) return TOUCH_2_TEMPLATE;
  if (touchNumber === 3) return TOUCH_3_TEMPLATE;
  return null;
}

export function renderTemplate(
  touchNumber: number,
  params: { firstName: string; company: string; topic: string }
): string {
  const template = getTemplateForTouch(touchNumber);
  if (!template) return '';
  return template.render(params);
}
